### ISSUE TITLE
Wrong semantic elements in chat posts

### ISSUE THREAD

**Issue by DominoPivot** [wxrod/Tumblr-HTML5-Blank-Theme#3]
The chat posts in this theme are made of `<dialog>` elements, which according to the HTML spec represent modal UI components (not conversations!). Using `<dt>` and `<dd>` also stretches the semantics as these usually represent glossary terms. A list or a table is probably a better idea, like this:

```
{block:Chat}
<article class="post chat">
  {block:Title}
  <header>
    <h2>{Title}</h2>
  </header>
  {/block:Title}
  <table>
    {block:Lines}
    <tr>
      <th class="{Alt} {UserNumber}">{block:Label}{Label}{/block:Label}</th>
      <td>{Line}</td>
    </tr>
    {/block:Lines}
  </table>
{/block:Chat}
```

**Comment by wxrod** [comment]
Good point @DominoPivot.
